### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/Authenticator#1]
**Is your feature request related to a problem? Please describe.**
Edit README.md to reflect the [2FA design doc](https://bit.ly/3AcD8m7)

**To-add**
- [ ] Project Overview (Shortened)
- [ ] Links
  - [ ]  design document
  - [ ] outside resources listed in Bibliography

**To-remove**
- [ ] Layout/readme
- [ ] Issues
- [ ] git specific stuff/linux and everything underneath
- [ ] conclusion

**Comment by alans-42** [comment]
I updated the readme to include information from the wiki and was wondering if I should make a pull request for others to review it before anything.

**Comment by emilkovacev** [comment]
Awesome! Yes, you should make a pull request, be sure to write the phrase `closes #1` in the pull request message, so it's linked with this issue
