### ISSUE TITLE
Project automation does not consider category when adding issues to project boards

### ISSUE THREAD

**Issue by WeirdAlex03** [makeopensource/Authenticator#10]
### Subject of the issue
-------------------------------------------
The 3 project boards all currently have a handful of issues in their to-do section that are not relevant to the board topic. As far as I can tell, GitHub's default automation system does not allow for filtering by label (and also there aren't any relevant labels to filter by anyway, but I assume #9 will take care of that). We would either need to add/make an action with more advanced controls or collect all new issues/PRs into a single project board to be manually sorted. For the latter, once an issue has been added, I *think* the automation system should be able to manage it correctly, but this will need testing.

### Expected behavior
-------------------------------------------
The Authentication, Secure Database Storage, and Visual Interface boards only contain issues relevant to them.

### Actual behavior
-------------------------------------------
All 3 boards contain irrelevant issues, which the activity logs indicate has all been done by board automation.

### Steps to reproduce
-------------------------------------------
1. Open [any](https://github.com/makeopensource/Authenticator/projects/1) [project](https://github.com/makeopensource/Authenticator/projects/2) [board](https://github.com/makeopensource/Authenticator/projects/3)
2. Look at the To do column
3. Note how the issues are not relevant to the board topic

### Any relevant logs, error output, etc?
-------------------------------------------
Board activity logs can individually be viewed by opening the board and opening the Menu

**Comment by emilkovacev** [comment]
I removed the automation feature from the project boards for now. I'm not super familiar with automating those, but moving forward with issues we should just label the appropriate project along with the issue, great catch! 😄

**Comment by emilkovacev** [comment]
Do you think we should have a "general" or "misc" category for other things in case they come up?

**Comment by WeirdAlex03** [comment]
> Do you think we should have a "general" or "misc" category for other things in case they come up?

I would say so, yeah.
