### ISSUE TITLE
Add Application Panel

### ISSUE THREAD

**Issue by jmabramo** [makeopensource/Authenticator#13]
Create a panel with the ability to use the camera to scan an application QR code to add it to the application list

- [ ] Scan QR code
- [ ] Parse data
- [ ] Store in applications list

Resources
https://github.com/react-native-camera/react-native-camera
https://github.com/moaazsidat/react-native-qrcode-scanner

**Comment by emilkovacev** [comment]
Here's additional documentation on switching between views for react-native

- https://reactnative.dev/docs/handling-touches
- https://reactnative.dev/docs/navigation

**Comment by mskravec** [comment]
Do you need any help with this? I wouldn't mind assisting however I can.
