### ISSUE TITLE
Settings Panel

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/Authenticator#7]
Add a settings panel for the app! The settings panel should be written in React Native

## List Items
All list items should include the appropriate widgets. Complex widgets and functionality may be split into another issue on request!

- [ ] Generate Back-up codes
- [x] Change UI (all UI settings)
- [x] Background-color
- [x] Font
- [x] Font-size
- [ ] Color-blindness settings
- [ ] Default app icon
- [ ] Username
- [ ] Account cloud back-up
- [x] User guide
- [x] Privacy Policy

**Comment by mattrrubino** [comment]
Here is what I came up with for the settings panel:

![settings_new](https://user-images.githubusercontent.com/83928138/148559747-f083bee6-6993-49c5-9d48-c3a2b3150f66.PNG)

We likely will not need the backup section since we are not supplying/storing backup codes, so I will probably remove this from the design. What do you think?

**Comment by emilkovacev** [comment]
I think this is a great start! I'm fine with removing the backup section for now, given that we will probably want to figure out a way to backup later. @ahanabhattchrya what are your thoughts?

**Comment by ahanabhattchrya** [comment]
This looks great! Would we like to keep the colors as black/white (i personally, am a big fan of that)? Thank you for the draft @mattrrubino !

**Comment by ahanabhattchrya** [comment]
If the UI is something we can finalize by this week, I can start working on the code!

**Comment by emilkovacev** [comment]
> This looks great! Would we like to keep the colors as black/white (i personally, am a big fan of that)? Thank you for the draft @mattrrubino !

I definitely think keeping the color scheme basic for now would be good, we can certainly revisit that later if need be. 
In the meantime, once matt makes a pull request, feel free to start functionality for each settings page! You can post updates on what you're working on either here or in discord so no one does the same functionality twice.

**Comment by mattrrubino** [comment]
Sounds good! I started implementing the color picker as well, which I ended up nesting inside the settings page itself. Should I make a PR with this?

![A6F57A5D-795F-4EF0-85F4-A4DA0022E478](https://user-images.githubusercontent.com/83928138/148600513-c423ffd3-8037-4d1d-bf5d-916654dc2cbb.png)

**Comment by emilkovacev** [comment]
Are those buttons dropdowns? We can discuss that, I personally prefer the buttons opening up individual views. Regardless I think you should make a PR and we can talk about improvements there before merging

**Comment by mattrrubino** [comment]
Yes, they are currently dropdowns. However, it would be relatively straightforward to turn them into their own views, which I agree would be the better solution. I'll make a PR with what I currently have and start working on giving each color setting its own view.

**Comment by mattrrubino** [comment]
I have looked into many packages, and it seems that none of them work for one reason or another. 

The [package](https://github.com/Naeemur/react-native-wheel-color-picker) used in this PR works about 50% of the time, but it often places the color selector outside of the color wheel and becomes completely unresponsive.
I also tried [this](https://github.com/yuanfux/react-native-hsv-color-picker) package, but it makes use of ViewPropTypes, which has been deprecated and is completely unsupported by newer version of the react-native-web package. This results in crashes for the web implementation.
[This](https://github.com/instea/react-native-color-picker) package is also popular, but I cannot get the slider component to work. The triangle color picker also jitters uncontrollably on iOS.
There are a lot of other color picker libraries, but they often only provide swatches or have no option to adjust lightness.

It may be worthwhile to consider some of our other available options. Should we implement our own color selection system, or opt for something simpler like swatches/palettes?

**Comment by emilkovacev** [comment]
I think, at least for now, opting for swatches is the way to go. As long as we have a large enough swatch collection, it shouldn't be a problem. Also, it avoids the potential pitfall of setting the background to a color that hides buttons and text, since we can carefully select which colors we want to include.
