### ISSUE TITLE
Label Library

### ISSUE THREAD

**Issue by emilkovacev** [makeopensource/Authenticator#9]
We need a set of labels that fits our workflow, is properly colored and named, and gives more information about each issue. *Please list relevant label categories under a LABELS.md file in the root directory.*

## Possible Label Categories
- [ ] Effort (1-3)
- [ ] Priority (1-3)
- [ ] Type (enhancement, documentation, bug, etc.)

Feel free to add more categories to this issue and/or the LABELS.md file as we move along

## Relevant Background Information
- https://seantrane.com/posts/logical-colorful-github-labels-18230/
- https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
- https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues
- https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by SaathvikT** [comment]
Hey @emilkovacev the above set of labels look good.

Based on them, the labels can be in the form of:

- priority - 1, 2, or 3 (With 1 having highest priority)

- Effort - 1,2, or 3 (With 3 requiring a significant effort)

Additional labels:

- feature - All usability features of the application should have this.

- bug - Bugs can be reported.

- Expedite - (Just a suggestion) We are in no way asking devs to spend a lot of time finishing a ticket quickly, but there can be situations where one ticket can be hindering the progress of others. It can turn into a roadblock for other devs. Can be useful in certain situations

**Comment by SaathvikT** [comment]
For the branches, devs can create a branch based on their ticket labels. 

For example, "feature/build-menu-bar" or "bug/fix-icon" etc...
This will create a folder structure of our branches and they can be organized easily.

**Comment by emilkovacev** [comment]
That looks really good! 👍 I have a few comments.
- Instead of using an expedite label, I think we should rely on priority tags to ensure that tasks get done in time. So an issue with `priority: high` should be prioritized over everything else, what are your thoughts on that? 
- Make sure that all labels and label groups have consistent capitalization
- I really like the idea of branching with tags, that would give a lot of description to branches and allow people to jump into existing issues more easily, I think we should move forward with that

**Comment by emilkovacev** [comment]
Are there any other categories we should consider before moving forward with the document?

**Comment by SaathvikT** [comment]
Cool!! 

Priority labels should be enough for devs to choose a ticket. I agree with the rest of the points as well.

I honestly think these categories should suffice. I'm sure we can always add a label if there's a requirement for it. Let's go ahead with document!!

**Comment by SaathvikT** [comment]
Let's also add branch naming conventions into the [Contributing.md](https://github.com/makeopensource/Authenticator/blob/master/CONTRIBUTING.md)

**Comment by emilkovacev** [comment]
Sounds good, would you like to setup the document, or should I just go ahead with it?
